### PR TITLE
Add some more AVX2 ops

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by nemequ** [comment]
Merged, thanks!

I rewrote some commit messages so the IDs won't match, but the code is the same.

**Comment by mr-c** [comment]
Thank you @nemequ !

Any guidance for adding AVX-512 operations?

**Comment by mr-c** [comment]
Oh, and could you use [`co-authored-by:`](https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) if you re-write commits? Would be nice for future contributors to see their username in the contributors list :-)

**Comment by mr-c** [comment]
nevermind, I was looking at the wrong commits :-D

**Pull request closed without merging**
