### PR TITLE
neon: get_lane implementation

### PR DESCRIPTION
**Pull request by seanptmaher**
I implemented get_lane and getq_lane.

I didn't spend the time to get a super good implementation on x86 (I did a quick look, and didn't seen any lane-extracting intrinsics, but I could have just been missing them) but honestly, I'm not too worried, as the autovectorizer should be getting this, it's very very simple. 

Anyways, as always, let me know if anything is missing. 
(CC @ngzhian @tlively)

### CODE REVIEW

**Comment by nemequ** [comment]
Can you hold off on this for a day or so?  I'm considering a hack which would let us do stuff like this, but require some fairly ugly macros.  If I decide to merge it only relatively minor changes to this patch would be required, in which case I wouldn't want you to waste your time.

**Comment by seanptmaher** [comment]
Sure, there's no shortage of stuff to work on, after all. Let me know.

**Comment by nemequ** [comment]
I pushed everything to the [wip/thaw branch](https://github.com/nemequ/simde/tree/wip/thaw).  Please take a look and let me know if it seems okay to you.  If you don't object I'll go ahead and merge it into master.

c8e2c8067ebffd5ab7e3379c1b8ba7e40e969ca7 is just to work around emscripten-core/emscripten#11419.  Hopefully I'll be able to revert that soon (or maybe drop it before it gets in at all).

**Comment by seanptmaher** [comment]
Oh, yeah, looks great to me. Thanks for the help.

**Pull request closed without merging**
