### PR TITLE
avx512{f,bw,vl}: Move all movm and mask{,z}_mov tests to avx512f

### PR DESCRIPTION
**Pull request by rosbif**
The intrinsics were moved so now move the tests.

### CODE REVIEW

**Comment by rosbif** [comment]
I restarted clang-10 a couple of times but I think that there is something wrong with the platform.

**Comment by rosbif** [comment]
@nemequ: Please would you kindly either merge this or tell me what is wrong so that I can correct it.
I am continuing to work on avx512f and I would like to rebase on the updated master before the merge becomes too complicated. TIA.

**Comment by nemequ** [comment]
Sorry.  I just sent another build off to CI which worked in my ci-noise repo, as soon as it's done building I'll merge it into master (assuming it's successful).  Luckily CI is a lot faster now, it's almost done :)

If it would help I can start just reviewing your PRs and letting you merge them.  You may have to rebase them from time to time, but at least I wouldn't be a bottleneck…

You seem to have adjusted pretty well to the conventions in SIMDe, IIRC I haven't really touched any of your recent commits.  If you're comfortable with a commit I'd also be comfortable with you just going ahead and merging it without a review.  If you aren't comfortable with something you can always request a review, or we can talk on Gitter if you just have questions.

**Comment by rosbif** [comment]
> Sorry. I just sent another build off to CI which worked in my ci-noise repo, as soon as it's done building I'll merge it into master (assuming it's successful). Luckily CI is a lot faster now, it's almost done :)
> 

Thank you.

> If it would help I can start just reviewing your PRs and letting you merge them. You may have to rebase them from time to time, but at least I wouldn't be a bottleneck…
> 
> You seem to have adjusted pretty well to the conventions in SIMDe, IIRC I haven't really touched any of your recent commits. If you're comfortable with a commit I'd also be comfortable with you just going ahead and merging it without a review. If you aren't comfortable with something you can always request a review, or we can talk on Gitter if you just have questions.
>

I seem to be plagued recently by test platform failures out of my control and expected statuses which are never returned. It is a long time since I obtained a clean sheet.
AIUI I shall only be allowed to merge if all tests pass successfully which at the moment is never :-(

**Comment by nemequ** [comment]
> I seem to be plagued recently by test platform failures out of my control and expected statuses which are never returned. It is a long time since I obtained a clean sheet.
> AIUI I shall only be allowed to merge if all tests pass successfully which at the moment is never :-(

Sorry.  I think the failures should be reduced now; the last week or so has been a bit rough, but AFAIK all the issues are fixed now.  You'll still see sporadic failures due to circumstances beyond our control, but I think you should have permission to restart most builds now; usually if you just wait an hour or so and try again it will work.  For example, I restarted that clang-10 build you mentioned earlier and it worked.

CI should also be a lot faster now that we've switched most builds to running the tests in parallel… I think Travis is about twice as fast, and the even SDE build on GitHub Actions is down to like 15 minutes, and I think we can reduce contention by making master not build on all CI providers (already the case for Travis, but now Drone seems to be our slowest build).  Hopefully that will smooth things out a bit since we don't need to try to batch up a bunch of patches.

**Pull request closed without merging**
