### PR TITLE
sse4.1: add NEON and AltiVec translations of *blend*; correct PPC versions globally

### PR DESCRIPTION
**Pull request by rosbif**
With PPC64 on qemu there is a problem with _mm_movemask_epi8. I think it is a qemu bug. Have you seen it before?

### CODE REVIEW

**Comment by rosbif** [comment]
I think I have now finished the NEON and AltiVec translations of the blend and blendv intrinsics.
That said, I just thought that maybe there are also some in AVX512*.
I shall check later.

**Comment by mr-c** [comment]
@rosbif Can you fix the merge conflict? That is stopping the CI from running. Thanks!

**Comment by rosbif** [comment]
@mr-c 
> @rosbif Can you fix the merge conflict? That is stopping the CI from running. Thanks!
>

I shall try but I am never sure of the best way to go about it, especially if you have changed my commits. Often I end up with the same modifications twice, once in my commit and once in yours.
Can you tell me the best way to go about it?

**Comment by rosbif** [comment]
I have roughly merged them but I have a problem.
I think Evan removed the SIMDE_X86_GENERATE_CONVERSION_FUNCTION generation for float and double because that is what caused the gcc ICE.
I thought he had replaced them by hand-coded functions.
But e.g. simde__m128d_to_altivec_f64 is missing so the code will no longer compile.

**Comment by rosbif** [comment]
I have pushed a merged version which is close to the one in master but with my PPC version corrections. It should be easier to merge.

N.B. I had to reintroduce the SIMDE_X86_GENERATE_CONVERSION_FUNCTION generation for float and double otherwise it won't compile even on clang.

**Pull request closed without merging**
