### PR TITLE
avx512f: added implementation for mm512_{,mask,maskz}_broadcastss_ps

### PR DESCRIPTION
**Pull request by masterchef2209**
avx512f: added implementation for mm512_{,mask,maskz}_broadcastss_ps

### CODE REVIEW

**Comment by nemequ** [comment]
Just FYI, instead of opening a PR to get CI to build you can just use a branch in this repo.  It works basically the same; push to a branch, CI builds, if it succeeds you can merge.  I'd suggest `hidayat/*` for the branch names.

**Comment by masterchef2209** [comment]
Thank You, I was not aware of it, I will do it that way from next time.

**Comment by masterchef2209** [comment]
I think I don't understand the right way to merge to master without opening a PR, can you please help me out, even when I push to a branch in main repo and if the tests passes, how to merge without a PR as main repo is protected so I cannot push to it.
Thank You

**Comment by nemequ** [comment]
> I think I don't understand the right way to merge to master without opening a PR, can you please help me out, even when I push to a branch in main repo and if the tests passes, how to merge without a PR as main repo is protected so I cannot push to it.
> Thank You

You probably needed to rebase.  The commit ID needs to be identical to a commit ID for which CI previously built successfully.  If any commits have made it into master prior to merging you'll need to rebase your commit(s) on top of that and put it through CI again.

If you want, send me a message next time you're ready to merge something and I'll walk you through it.

**Pull request merged**
