### PR TITLE
gfni: Add fallbacks and clean up.

### PR DESCRIPTION
**Pull request by rosbif**
N.B. The "inverse" fallbacks may not be faster, particularly for 128-bit.
I'll test this later and disable them if necessary but it will be highly platform dependent.

### CODE REVIEW

**Comment by rosbif** [comment]
AFAICS Travis-CI passed but it is still waiting for status to be reported.

@nemequ: Are you ready for NEON stuff?
Otherwise, if this pans out, what should I do now?
(I think that there is probably more movm, mask_mov and maskz_mov stuff to do and their integration into other mask and maskz intrinsics.)

**Comment by rosbif** [comment]
I don't seem to be able to restart these tests (I suppose I could send a dummy commit but I don't like the idea).
Well finally I just removed the executable file mode bits from avx2.c.

**Comment by nemequ** [comment]
> AFAICS Travis-CI passed but it is still waiting for status to be reported.

Yeah, something is up with Travis.  It hasn't been building PRs :(

The changes look great, thanks!

I've pushed this to a branch to get it to build; I had to make a few minor adjustments (good news: I made it *even harder* to get through CI!  The clang-10 build now includes -Weverything -Werror), but nothing substantial.  I think you'll like them, it's basically about using unsigned integers (and `simde_mm*_set_epu*` instead of `simde_mm*_set_epi*`).  I'll merge as soon as CI is finished.

Other than that, my only nit to pick is please add a blank line between the commit log summary line and the description.  Lots of tooling, including internal git stuff like `git rebase -i`, expects it and doesn't behave well if you omit it.

> @nemequ: Are you ready for NEON stuff?

Not yet, sorry.  I'll try to get to that soon, but it is going to take a bit of time.  Once I do it should be a lot easier to add NEON functions, though; I plan to generate pretty much everything except for the actual portable implementations automatically.

> Otherwise, if this pans out, what should I do now?

Whatever you think would be fun and/or interesting.  The most important thing when working on open source software is to work on something you enjoy.  Everyone enjoys different things, so I'm not really sure what to suggest for you, but ideas include:

If implementing NEON functions is your goal but you're not yet familiar with it, then probably the best thing to do to get ready for that would be using NEON to implement SSE/AVX functions.  You could also do the same for WASM or POWER, or start adding ARM SVE implementations (which would be awesome for AVX-512F).

If that doesn't interest you, obviously there are still *lots* of AVX-512F instructions to get through.  VBMI and BITALG look like they'd be fun, though a lot of them will probably be impossible to vectorize (like the VPCOMPRESS* stuff).

Or, if you want to fight with compilers you could try to get PGI working in C++ mode, or work around compiler bugs on different architectures.

Basically, just take a look at the issue tracker and see if anything sounds interesting.

> What do you understand by the + here?

it's `&&` not `||` :(

> In fact it seems thar VL never appears alone. It is generally accompanied by F, BW or DQ but also sometimes by more esoteric ones. It seems to appear in anything that isn't 512-bit. Does it stand for Variable Length or Vector Length or what?

Vector Length.  VL extends AVX-512 to cover 128-bit and 256 bit vectors.

Actually, I seem to remember Wikipedia has a helfpul article here… yep, [AVX-512](https://en.wikipedia.org/wiki/AVX-512#Instruction_set) has a list of the extensions and a very brief description.  And I really wish I had remembered that before I got half-way through typing out my own descriptions of each…

> I am therefore thinking of moving them all to F and restoring what seems a more natural order of includes: VL includes BW (which includes F).

I'm not opposed to moving them into F.  In fact, IIRC I just moved a few there a day or two ago.

That said, I don't know why you think VL -> BW -> F is a more natural ordering than BW -> VL -> F.  BW is for operations on 8/16 bit lanes, and VL is for operations on 128/256 bit vectors.  I don't really see either as a more natural choice for a higher level.  I'm open to persuasion here, I just haven't seen it up until now.

The way I see it, F is the lowest level (I don't think anyone is going to argue otherwise).  On top of that there is VL and BW, and I think everything builds on one or more of those.

> However I think the tests should go in the "highest level" referenced.
> What do you think?

I don't have a strong opinion; I've been putting the tests in the corresponding *.c file for the *.h file the functions are in.  I guess this would all depend on whether you view VL and BW as siblings or not (which I do).  For other extensions I think it's much less ambiguous; if something is AVX512VL + GFNI, for example, GFNI is clearly the right place for both he implementation and test.

I'll grant that it's a bit weird to have BW+VL functions in the F tests just because they happen to be handy for implementing functions that are in F.  I could probably be convinced that, for example, an F+BW test belongs in BW even if the implementation is in F, but what do you do for a BW+VL function with an implementation in F?

That said, I feel like these are really implementation details that don't matter much to anyone other than those of us working on SIMDe, so I'm not all **that** concerned with getting it "right".

**Comment by rosbif** [comment]
Sorry for the stray semicolons on a couple of macros ;-(

> Other than that, my only nit to pick is please add a blank line between the commit log summary line and the description. Lots of tooling, including internal git stuff like `git rebase -i`, expects it and doesn't behave well if you omit it.
> 

Do you mean add a blank second line in the editor started by `git commit`?

> If implementing NEON functions is your goal but you're not yet familiar with it, then probably the best thing to do to get ready for that would be using NEON to implement SSE/AVX functions. You could also do the same for WASM or POWER, or start adding ARM SVE implementations (which would be awesome for AVX-512F).
> 

Actually I was thinking of the opposite: implementing NEON using SSE like Victoria's excellent NEON2SSE.

> > I am therefore thinking of moving them all to F and restoring what seems a more natural order of includes: VL includes BW (which includes F).
> 
> I'm not opposed to moving them into F. In fact, IIRC I just moved a few there a day or two ago.
> 
> That said, I don't know why you think VL -> BW -> F is a more natural ordering than BW -> VL -> F. BW is for operations on 8/16 bit lanes, and VL is for operations on 128/256 bit vectors. I don't really see either as a more natural choice for a higher level. I'm open to persuasion here, I just haven't seen it up until now.
> 
> The way I see it, F is the lowest level (I don't think anyone is going to argue otherwise). On top of that there is VL and BW, and I think everything builds on one or more of those.
> 

Yes you're right. In any case VL, BW and DQ always go together on processors.

> > However I think the tests should go in the "highest level" referenced.
> > What do you think?
> 
> I don't have a strong opinion; I've been putting the tests in the corresponding *.c file for the *.h file the functions are in. I guess this would all depend on whether you view VL and BW as siblings or not (which I do). For other extensions I think it's much less ambiguous; if something is AVX512VL + GFNI, for example, GFNI is clearly the right place for both he implementation and test.
> 
> I'll grant that it's a bit weird to have BW+VL functions in the F tests just because they happen to be handy for implementing functions that are in F. I could probably be convinced that, for example, an F+BW test belongs in BW even if the implementation is in F, but what do you do for a BW+VL function with an implementation in F?
> 

If I put them in F I don't think that the tests for VL, BW and DQ intrinsics should be in F because the (bizarre) Knights* processors have F without the others.

> That said, I feel like these are really implementation details that don't matter much to anyone other than those of us working on SIMDe, so I'm not all **that** concerned with getting it "right".

Great!

**Comment by nemequ** [comment]
> I don't seem to be able to restart these tests (I suppose I could send a dummy commit but I don't like the idea).
> Well finally I just removed the executable file mode bits from avx2.c.

Ugh, sorry, I just saw this.  Now I understand why GitHub was fighting me when I pressed the "Comment" button earlier; there was a new comment :(

I'll add a check to the "formatting" test in GitHub actions to make sure none of the *.c/*.h files are executable, and merge your fix.

> and pushed again resulting in this mess.
> What should I have done?

To clean up the commit?  After you `git add` your changes, `git commit --amend` will amend the previous commit instead of creating a new one.  You can then use `git push -f` to force push to the branch.  GitHub will generate a bit of noise, but the git repository will be nice and clean.

Of course, I usually just squash commits like this anyways when I merge, so if you just use your normal workflow it's not really a problem for me.

> Do you mean add a blank second line in the editor started by git commit?

Yes. There is [an example](https://github.com/nemequ/simde/blob/master/CONTRIBUTING.md#commit-messages) in CONTRIBUTING.md.

> Actually I was thinking of the opposite: implementing NEON using SSE like Victoria's excellent NEON2SSE.

I know, but that's what is blocked on me finishing the code generator.  What I was trying to say was that using NEON to implement SSE would help you learn NEON (if you're not already familiar with it) so when you start going in the other direction you should have an easier time, and of course you don't have to wait for me.

> If I put them in F I don't think that the tests for VL, BW and DQ intrinsics should be in F because the (bizarre) Knights* processors have F without the others.

I've been pretty much ignoring the KN* stuff.  My understanding is that it's pretty much dead (I believe Intel has even deprecated support in ICC), so it really just adds a lot of complication for something very few people would find useful.

Anyways, I don't see why that would be a problem.  It doesn't hurt anything to have a test for a function without a native implementation.

**Pull request closed without merging**
