### PR TITLE
Add SSE* fallbacks and correct typos

### PR DESCRIPTION
**Pull request by rosbif**
Add SSE2 fallbacks for the following functions:-
simde_mm256_cmpeq_epi8()
simde_mm256_movemask_epi8()
simde_mm256_srli_epi64()

Add SSSE3 fallbacks for the following function:-
simde_mm256_shuffle_epi8()

Correct typos:-
s/SIMDE_AVX22_ENABLE_NATIVE_ALIASES/SIMDE_AVX2_ENABLE_NATIVE_ALIASES/

### CODE REVIEW

**Comment by rosbif** [comment]
Sorry, it also includes my previous PR which hasn't been merged yet.
How do I prevent this?

**Comment by junaruga** [comment]
I do not think that sending pull-request from your forked repository's master branch is a good habit.
Because the master can be used to sync from the upstream remote repository. And when using the master branch for that, you can send multiple pull-request from your forked repository.

I recommend that you close this PR, and create the new pull-request (PR) by following way.

I assume you are on master branch setting only origin as your forked repository.

```
$ git remote -v
origin	git@github.com:rosbif/simde.git (fetch)
origin	git@github.com:rosbif/simde.git (push)

$ git branch
*  master
```

Create current master's bask up like this. Then move to master branch again.

```
$ git checkout -b master-backup
$ git checkout master
```

Delete your latest 2 commits used for this PR, and download the latest master commits to your local.

```
$ git reset --hard HEAD^^
$ git pull
```

Create a new (topic) branch for the pull-request. The branch name can include the pull-request's subject. You can see [this](https://nvie.com/posts/a-successful-git-branching-model/) for the general branchinig model. In this case, for example, `someting`, `feature/something` or `hotfix/something`.

```
$ git checkout -b <your topic branch name>
```

Now you are on the `<your topic branch name>` branch.
Merge your `master-backup`'s commit to the `<your topic branch name>` branch.

```
$ git cherry-pick <commit_hash>
```

Then send pull-request from GitHub UI again.

Delete master-backup branch.

```
$ git branch -D master-backup
```

That's it for this case.

In general, this document [How to create a pull request in GitHub](https://opensource.com/article/19/7/create-pull-request-github) might be good to see. :)

**Comment by junaruga** [comment]
I can also recommend `git rebase -i <commit hash>` to modify your commit.

**Comment by rosbif** [comment]
Thank you Jun for your detailed help.
I'm afraid I hadn't seen the document you mention.

**Comment by junaruga** [comment]
It's okay.

> download the latest master commits to your local.

My steps for `git pull` is not enough to get the "latest" master from the "nemequ/simde" repository.

`git remote add <url>` and `git pull <repository> master` help you.

**Comment by rosbif** [comment]
I submitted again and failed miserably.
I think that one of my mistakes was to RTFM (How to create a pull request in GitHub) !
It says "$ git push -u origin new_branch".
Shouldn't that be "$ git push -u **upstream** new_branch"?

**Comment by junaruga** [comment]
> It says "$ git push -u origin new_branch".
> Shouldn't that be "$ git push -u upstream new_branch"?

According to the document at OpenSource.com I introduced.

`$ git push -u origin new_branch` is correct. `$ git push -u upstream new_branch` is wrong.

Check your the result of `git remote -v`.

Because in this document `git clone https://github.com/<YourUserName>/demo` means your forked repository that is as set `origin`.
`git remote add upstream https://github.com/kedark3/demo` it set as `upstream`.

So, the result of the document expects like this.

```
$ git remote -v
origin	https://github.com/rosbif/simde.git (fetch)
origin	https://github.com/rosbif/simde.git (push)
upstream	https://github.com/nemequ/simde.git (fetch)
upstream	https://github.com/nemequ/simde.git (push)
```

You have a permission to push for `origin`. But you do not have the permission to push for `upstream`.
This is the way in the document.

---

By the way, in my case I am using the opposite way of the document. I am seting downstream by `git remote add` after `git clone git@github.com:nemequ/simde.git`.

```
$ git remote -v
junaruga	git@github.com:junaruga/simde.git (fetch)
junaruga	git@github.com:junaruga/simde.git (push)
origin	git@github.com:nemequ/simde.git (fetch)
origin	git@github.com:nemequ/simde.git (push)
```

**Comment by rosbif** [comment]
Sorry for being thick.
I have origin and upstream the other way round.
That is because I started long ago by cloning nemequ/simde to try it out and add my modifications locally.
I only created my fork a couple of days ago in order to share my work.
As I couldn't push to origin I set upsteam to my fork.
(I am more familiar with sending modifications as patches rather than PRs.)
Sorry again for being stupid.

**Comment by junaruga** [comment]
It's okay. Everyone is or was a beginner when starting a new thing. I had not been familiar with PRs too for years after staring learning git and GitHub.

> That is because I started long ago by cloning nemequ/simde to try it out and add my modifications locally.
> I only created my fork a couple of days ago in order to share my work.

It's a common use case. So, to be honest, I would recommend more my way (and your way) setting a forked repository later by `git remote add` when it is necessary, rather than the way in the document.

**Pull request closed without merging**
