### PR TITLE
avx512vl.h: add fallbacks for _mm{,256}_{movm,mask_mov,maskz_mov}_epi{16,32}

### PR DESCRIPTION
**Pull request by rosbif**
I probably haven't finished with these but they pass Travis-CI and "release early, release often" ;-)

### CODE REVIEW

**Comment by rosbif** [comment]
I just noticed that direct tests for _mm{,256}_movm_epi{16,32} are missing.
They are tested indirectly by the other intrinsics but I'll add direct tests.
I also notice that I can no longer push new additions to this branch.
Git tells me to pull first but last time I did that before pushing again it created double commits.
If I try to rebase it says I am already up to date.
Should I fetch then rebase or what?

**Comment by mr-c** [comment]
@rosbif It is because I added a merge commit. So `git fetch` followed by a rebase should fix it

**Comment by rosbif** [comment]
I also note that in the IIG _mm{,256}_movm_epi32 are specified as AVX512VL + AVX512DQ but are useful for creating _mm{,256}_mask{,z}_mov_epi32 which are specified as AVX512VL + AVX512F.
So I suppose putting them in avx512vl.h is not too unreasonable.
They, in turn, are also useful in avx512bw.h but Evan resolved this by having avx512bw.h include avx512vl.h rather than vice-versa.

**Comment by nemequ** [comment]
> I also note that in the IIG _mm{,256}_movm_epi32 are specified as AVX512VL + AVX512DQ but are useful for creating _mm{,256}_mask{,z}_mov_epi32 which are specified as AVX512VL + AVX512F.
> So I suppose putting them in avx512vl.h is not too unreasonable.
> They, in turn, are also useful in avx512bw.h but Evan resolved this by having avx512bw.h include avx512vl.h rather than vice-versa.

I'm not sure if you were looking for a reply here or not.  AFAICT it seems like vl works for everything, but honestly if we need to put them in f that would be okay with me.  The different files for each avx512* extension is really mostly about not having ~ 50 kloc in one file when we're done.  Intel just uses one file for everything after AVX anyways…

**Comment by rosbif** [comment]
> I'm not sure if you were looking for a reply here or not.
>

Sorry I was thinking aloud.
I started thinking there was going to be a real problem with avx512dq.h but in the end I also convinced myself that it was OK.
Sorry again for the noise, I should have deleted the message.

**Comment by nemequ** [comment]
No worries.  i don't mind, I just wasn't sure if you were looking for a reply :)

Thanks for the patches!  The code changes look good up to the latest batch look good, I merged them unaltered.  I'll take a look at the latest ones soon.

I did squash a couple commits and tweaked a few of the commit messages; the component name shouldn't be a file (e.g., avx512vl instead of avx512vl.h), and all lines (including the summary) should be 72 characters or less.  It's a pretty common format, based loosely on [the Linux Kernel](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst#n648) if you want to read an explanation of why.

**Comment by rosbif** [comment]
I notice there is a native alias problem. Probably a C&P error. I'll look.

Sorry I've been having a bit of a problem with the shift functions I've added to avx2.h on some platforms. I'll sort them out.
Maybe you know whether this sort of construct is legal in SIMDE_VECTOR_SUBSCRIPT_SCALAR:
`r_.u32 = (b_.u32 < 32) ? (a_.u32 << b_.u32) : 0;`

As for the 72 characters: you are speaking to someone who has had the misfortune to work for many years on a Teletype ASR33. So I know all about 72 columns. Pity it has subsisted.
Should I also limit code, especially comments, to 72 columns?
(I have also loaded whole operating systems through the ASR33's perforated paper tape reader at 110 bauds.)

**Comment by nemequ** [comment]
Okay, just let me know when you're ready.

Unfortunately I just made some *very* noisy changes, so there are a lot of conflicts right now.  They're not major changes, I just renamed all the macros with double-underscores in them, so they're pretty straightforward to fix.

I just merged your latest changes, plus `s/ && 0//` and put them in a `wip/rosbif` branch.  If you're havivg problems because of all the conflicts you can work from there, otherwise as soon as you're done I'll merge your changes into that then merge into master.

> Should I also limit code, especially comments, to 72 columns?

It's nice, but it's more of a guideline than a rule.  If you have a good opportunity for a line break without making the code horribly ugly you should take it, but if it just makes the code more ugly feel free to run past 72 colums.

For comments I tend to be a bit better about sticking to 72 columns just because English tends to have more opportunities for wrapping than code.  But here, too, if you need to go past 72 for any reason feel free.

For commit messages I like to be a bit more strict.  While people these days are probably using grapthical editors for coding, interacting with git on the command line is (I think) the norm, and terminals are more likely to be a pain to deal with for long lines.  For the summary line I'm *very* strict about the 72 characters (I know a lot of projects actually limit you to 50 characters), since it helps keep `git log --oneline` usable.

**Comment by rosbif** [comment]
I hate MSVC ;-)
I have some improvements to avx512.h which I have held back because they depend on the shift functions I have added to avx2.h
I also have some gfni.h improvements rotting away which will need some rebasing.

Should I push this stuff or wait?

**Comment by rosbif** [comment]
> Maybe you know whether this sort of construct is legal in SIMDE_VECTOR_SUBSCRIPT_SCALAR:
> `r_.u32 = (b_.u32 < 32) ? (a_.u32 << b_.u32) : 0;`

Apparently it isn't.
Does anyone know how to write that in SIMDE_VECTOR_SUBSCRIPT_SCALAR?

**Comment by nemequ** [comment]
> I hate MSVC ;-)

Don't get me started.

> I have some improvements to avx512vl.h which I have held back because they depend on the shift functions I have added to avx2.h
> I must also try re-enabling the vector stuff in avx2.h.
> Did it pass the tests with the `&& 0 `removed?

Doesn't look like it: https://github.com/nemequ/simde/tree/wip/rosbif

If you look in the summary for the latest commit (the light blue bar right above the list of files), toward the right side is a small red X, which means CI failed.  You can click it to get a summary.

Note that this icon may also be a greet check (if CI passed) or an orange circle (if CI is still running).

> I also have some gfni.h improvements rotting away which will need some rebasing.
> 
> Should I push this stuff or wait?

Normally I'd say push so I can get started on rebasing, but let's finsih this patch set up first.  I'll add your latest changes to the wip/rosbif branch, then can you work on getting that to pass CI?

Once that's done you can submit your gfni improvements and I'll rebase those for you.  It doesn't seem fair to make you rebase a bunch of stuff that only needs to be rebased because I decided to makes some changes that tough a few thousand lines of code.

**Comment by nemequ** [comment]
> Does anyone know how to write that in SIMDE_VECTOR_SUBSCRIPT_SCALAR?
> Where is the syntax described?
> (It certainly isn't C.)

https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html

I believe something like this should work:

```c
r_.u32 = (b_.u32 < 32) ? (a_.u32 << b_.u32) : ((__typeof__(r_.u32)) { 0, });
```

But I haven't tested.  You may also have to explicitly initialize each element in the new vector (or you could just use `(a_.u32 ^ a_.u32)`)

**Comment by nemequ** [comment]
Okay, `wip/rosbif` should have all your changes and all conflicts resolved.

**Comment by rosbif** [comment]
Thanks

> > Does anyone know how to write that in SIMDE_VECTOR_SUBSCRIPT_SCALAR?
> > Where is the syntax described?
> > (It certainly isn't C.)
> 
> https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html
> 

For information this seems to work:
`r_.u32 = (b_.u32 < 32) & (a_.u32 << b_.u32);`

**Comment by rosbif** [comment]
I think I have finished this round if the tests pan out OK.
(xlc failed but I don't think it is my fault. I restarted it and all Travis-CI is green now.)
I shall no longer touch this branch.
But it is getting late so if there is a problem it will have to wait till tomorrow.
Sorry it has taken so long.

For the future I have improvements to gfni.h which is nearly finished and NEON stuff which is embryonic.

@nemequ: Would you please give feedback (even negative ;-)) on what I did here #265 (comment) ?
See also the previous messages.
TIA.

**Comment by rosbif** [comment]
The native aliases and AppVeyor failures seem to be for an earlier version :-(
I think that these were corrected last night.

**Comment by nemequ** [comment]
> The native aliases and AppVeyor failures seem to be for an earlier version :-(
> I think that these were corrected last night.

I'm running a rebased version through CI now, it's looking good so far.  It's in the wip/rosbif branch if you want to take a look.

**Comment by rosbif** [comment]
> > The native aliases and AppVeyor failures seem to be for an earlier version :-(
> > I think that these were corrected last night.
> 
> I'm running a rebased version through CI now, it's looking good so far. It's in the wip/rosbif branch if you want to take a look.

Thank you.
I restarted s390x which failed for other reasons I think.
(I was surprised that it allowed me to do this.)

**Comment by nemequ** [comment]
> I restarted s390x which failed for other reasons I think.
> (I was surprised that it allowed me to do this.)

You're listed as a collaborator on this project, so you have permission to restart jobs.  You can't restart jobs in repos you don't have write access to, not even your own PRs (you have to push an update to trigger a rebuild).

**Comment by nemequ** [comment]
Merged, thanks for the patch!

**Pull request closed without merging**
